name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'pack.zip'
          exclusions: '*.git* /docs/ LICENSE'
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'minolio-pack.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
